version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    command: ["--port", "8000", "--host", "0.0.0.0"]

  worker:
    build:
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    deploy:
      replicas: 2
    command: [
      "-A", "dtq.app", "worker", "--concurrency", "2", "-Q", "celery",
      "-l", "INFO", "-f", "celery.log"
    ]

  other-worker:
    build:
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    deploy:
      replicas: 1
    command: [
      "-A", "dtq.app", "worker", "-n", "other@%h", "--concurrency", "1", "-Q", "other",
      "-l", "INFO", "-f", "celery.log"
    ]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.12.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    command:
      - "celery"
      - "--broker=amqp://guest@rabbitmq:5672//"
      - "flower"
      - "--broker_api=http://guest:guest@rabbitmq:15672/api//"
    depends_on:
      - rabbitmq
