FROM python:3.9.15-slim

WORKDIR /opt

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN pip install setproctitle
RUN apt-get update && apt-get install -y procps

COPY /task_queue/ ./task_queue/

ENTRYPOINT ["celery"]
