FROM python:3.9.15-slim

WORKDIR /opt

COPY ./dtq/requirements.txt dtq-requirements.txt
COPY ./api/requirements.txt api-requirements.txt
RUN pip install -r dtq-requirements.txt
RUN pip install -r api-requirements.txt

COPY ./dtq ./dtq
COPY ./api .

EXPOSE 8000

ENTRYPOINT ["uvicorn", "main:app"]
